name: Delete All Files

on:
  workflow_dispatch:  # Puedes ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete everything except .github folder
        run: |
          shopt -s extglob
          rm -rf !(.git|.github)

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "🔥 Delete all files"
          git push
