name: Crear archivo .txt después de 15 minutos

on:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Crear archivo .txt
        run: |
          CURRENT_TIME=$(date +%Y%m%d%H%M%S)
          echo "Archivo creado a las $CURRENT_TIME" > "file_created_${CURRENT_TIME}.txt"

      - name: Commit and push the file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "file_created_${CURRENT_TIME}.txt"
          git commit -m "Crear archivo .txt después de 15 minutos"
          git push https://xprodaman:${{ secrets.GITHUB_TOKEN }}@github.com/xprodaman/kjhdsiyv.git
