name: Crear archivo .txt después de 15 minutos

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora (en UTC)
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Crear archivo .txt después de 15 minutos
        run: |
          sleep 900  # Esperar 15 minutos (900 segundos)
          echo "Archivo creado a las $(date)" > "file_created_$(date +%Y%m%d%H%M%S).txt"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "file_created_$(date +%Y%m%d%H%M%S).txt"
          git commit -m "Crear archivo .txt después de 15 minutos"
          git push
