name: Crear archivo .txt

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora (en UTC)
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Crear archivo .txt
        run: |
          CURRENT_TIME=$(date +%Y%m%d%H%M%S)
          echo "Archivo creado a las $CURRENT_TIME" > "file_created_${CURRENT_TIME}.txt"
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "file_created_${CURRENT_TIME}.txt"
          git commit -m "Crear archivo .txt"
          git push
